version: 2.1
orbs:
  ruby: circleci/ruby@01.1.1
  heroku: circleci/heroku@1.2.0

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:9.5-alpine
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: |
            gem install bundler
            bundle -v
      - run: bundle install
      - run: sudo apt install -y postgresql-client || true
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bundle exec rspec
